<a href="https://colab.research.google.com/github/drshahizan/Python-big-data/blob/main/assignment/ass6/bdm/F4_2/Assignment_6_Mastering_Big_Data_Handling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Game Recommendations on Steam
[Kaggle Link](https://www.kaggle.com/datasets/antonkozyriev/game-recommendations-on-steam)



A dataset of games, users and reviews for building recommendation systems

The dataset contains over 38 million cleaned and preprocessed user recommendations (reviews) from a Steam Store - a leading online platform for purchasing and downloading video games, DLC, and other gaming-related content. Additionally, it contains detailed information about games and add-ons.

Team members name:

LEE SEOW MING THERESA (MCS231013)\
SITI NORAFIZAH BINTI AB AZIZ (MCS231018)

##Loading Dataset

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# Upload the kaggle Token

from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"sitinorafizah","key":"b0e3fb68b882ec542c5a04f27197a87d"}'}

In [3]:
! pip install kaggle --quiet
! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json
! kaggle datasets list

ref                                                             title                                             size  lastUpdated          downloadCount  voteCount  usabilityRating  
--------------------------------------------------------------  -----------------------------------------------  -----  -------------------  -------------  ---------  ---------------  
thedrcat/daigt-v2-train-dataset                                 DAIGT V2 Train Dataset                            29MB  2023-11-16 01:38:36           1715        174  1.0              
derrekdevon/real-estate-sales-2001-2020                         Real Estate Sales 2001-2020                       28MB  2023-12-07 15:36:26           1068         28  1.0              
muhammadbinimran/housing-price-prediction-data                  Housing Price Prediction Data                    763KB  2023-11-21 17:56:32           7574        137  1.0              
jocelyndumlao/cardiovascular-disease-dataset                    Cardiovascu

In [4]:
!kaggle datasets download -d ANTONKOZYRIEV/game-recommendations-on-steam

100% 617M/618M [00:07<00:00, 83.4MB/s]
100% 618M/618M [00:07<00:00, 86.5MB/s]


In [5]:
# Unzip folder downloaded
!unzip -u '/content/game-recommendations-on-steam.zip'

Archive:  /content/game-recommendations-on-steam.zip
  inflating: games.csv               
  inflating: games_metadata.json     
  inflating: recommendations.csv     
  inflating: users.csv               


In [6]:
import pandas as pd
import numpy as np

df_game= pd.read_csv('/content/games.csv')
df_rec = pd.read_csv('/content/recommendations.csv')
df_users = pd.read_csv('/content/users.csv')

In [7]:
df_game.info()
df_rec.info()
df_users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50872 entries, 0 to 50871
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   app_id          50872 non-null  int64  
 1   title           50872 non-null  object 
 2   date_release    50872 non-null  object 
 3   win             50872 non-null  bool   
 4   mac             50872 non-null  bool   
 5   linux           50872 non-null  bool   
 6   rating          50872 non-null  object 
 7   positive_ratio  50872 non-null  int64  
 8   user_reviews    50872 non-null  int64  
 9   price_final     50872 non-null  float64
 10  price_original  50872 non-null  float64
 11  discount        50872 non-null  float64
 12  steam_deck      50872 non-null  bool   
dtypes: bool(4), float64(3), int64(3), object(3)
memory usage: 3.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38354101 entries, 0 to 38354100
Data columns (total 8 columns):
 #   Column          Dtype  
--

### Original data memory running RAM usage
System RAM Usage: 63.9%


In [8]:
pip install psutil

In [9]:
pip install memory-profiler

###Original data processing time

Processing Time: 0.40233731269836426 seconds

Data size:

*   df_game: 3.7+ MB
*   df_rec: 2.0+ GB
*   df_users: 315.6 MB

In [ ]:
import time
import psutil

# Calculate Processing time
start_time = time.time()

df_game= pd.read_csv('/content/games.csv')

end_time = time.time()

elapsed_time = end_time - start_time
print(f"Processing Time: {elapsed_time} seconds")

# Get CPU and memory usage
cpu_usage = psutil.cpu_percent(interval=1)
memory_usage = psutil.virtual_memory()

print(f"CPU Usage: {cpu_usage}%")
print(f"Memory Usage: {memory_usage.percent}%")

# Check system RAM usage
ram_usage = psutil.virtual_memory().percent
print(f"System RAM Usage: {ram_usage}%")

Processing Time: 0.40233731269836426 seconds
System RAM Usage: 63.9%


%time df5.loc['df_game','df_rec', 'df_users'].compute()

In [ ]:
df_game.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50872 entries, 0 to 50871
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   app_id          50872 non-null  int64  
 1   title           50872 non-null  object 
 2   date_release    50872 non-null  object 
 3   win             50872 non-null  bool   
 4   mac             50872 non-null  bool   
 5   linux           50872 non-null  bool   
 6   rating          50872 non-null  object 
 7   positive_ratio  50872 non-null  int64  
 8   user_reviews    50872 non-null  int64  
 9   price_final     50872 non-null  float64
 10  price_original  50872 non-null  float64
 11  discount        50872 non-null  float64
 12  steam_deck      50872 non-null  bool   
dtypes: bool(4), float64(3), int64(3), object(3)
memory usage: 3.7+ MB


In [ ]:
# Merge df_rec and df_users based on 'user_id'
merged_df = pd.merge(df_rec, df_users, on='user_id')

# Drop duplicate 'user_id' column and 'funny' column
merged_df = merged_df.drop(columns=['user_id', 'funny'])

# Display the resulting DataFrame
merged_df.head(2)

app_id  helpful        date  is_recommended  hours  review_id  products  \
0   975370        0  2022-12-12            True   36.3          0        28   
1  1817190        0  2022-11-27            True   32.2     969453        28   

   reviews  
0        5  
1        5

In [ ]:
# Drop rows with missing values
merged_df = merged_df.dropna()
print(merged_df.isnull().sum())

app_id            0
helpful           0
date              0
is_recommended    0
hours             0
review_id         0
products          0
reviews           0
dtype: int64


###Load Less Data:
Strategically load only the essential portions of the dataset to optimize memory usage.

The False value in 'Mac' and 'Linux' is more than True around 74.41% and 82.23%, so decided to load data without colum 'Mac' and 'Linux' of game.csv.
*   Processing Time has reduced from 0.40233731269836426 to 0.22 seconds.
*   System RAM Usage has reduced from 63.9% to 61.57%.
*   Memory usage has reduced from 3.7+ MB to 3.6+ MB.

In [ ]:
import time
import psutil

# Record start time
start_time = time.time()

# Load games.csv without 'mac' and 'linux' columns
df_load = pd.read_csv('/content/games.csv', usecols=lambda col: col not in ['mac', 'linux'])

# Record end time
end_time = time.time()

# Display DataFrame info
print("DataFrame 'df_load' Info:")
print(df_load.info())

# Display system RAM usage as a percentage
ram_percentage = (psutil.virtual_memory().used / psutil.virtual_memory().total) * 100
print("\nSystem RAM Usage:")
print(f"Used RAM: {ram_percentage:.2f}%")

# Display DataFrame memory usage as a percentage
df_memory_percentage = (df_load.memory_usage().sum() / psutil.virtual_memory().total) * 100
print("\nDataFrame Memory Usage:")
print(f"Used Memory: {df_memory_percentage:.2f}%")

# Display processing time
print("\nProcessing Time:")
print(f"Time taken: {end_time - start_time:.2f} seconds")

DataFrame 'df_load' Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50872 entries, 0 to 50871
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   app_id          50872 non-null  int64  
 1   title           50872 non-null  object 
 2   date_release    50872 non-null  object 
 3   win             50872 non-null  bool   
 4   rating          50872 non-null  object 
 5   positive_ratio  50872 non-null  int64  
 6   user_reviews    50872 non-null  int64  
 7   price_final     50872 non-null  float64
 8   price_original  50872 non-null  float64
 9   discount        50872 non-null  float64
 10  steam_deck      50872 non-null  bool   
dtypes: bool(2), float64(3), int64(3), object(3)
memory usage: 3.6+ MB
None

System RAM Usage:
Used RAM: 61.57%

DataFrame Memory Usage:
Used Memory: 0.03%

Processing Time:
Time taken: 0.22 seconds


###Use Chunking:
Process the data in smaller pieces to avoid memory issues.

In order to concat for all 3 csv files, the chunking technique has been used, the original file unable to merge all the 3 csv files as it will cause system RAM clash.

*   Processing Time is 224.17 seconds.
*   System RAM Usage is 7.40% / 13.1 MB

In [ ]:
import pandas as pd

# Define chunk size
chunk_size = 10000

# Create iterators for each CSV file
games_iter = pd.read_csv('/content/games.csv', chunksize=chunk_size)
rec_iter = pd.read_csv('/content/recommendations.csv', usecols=['app_id', 'helpful', 'funny', 'date', 'is_recommended', 'hours', 'user_id', 'review_id'], chunksize=chunk_size)
users_iter = pd.read_csv('/content/users.csv', usecols=['user_id', 'products', 'reviews'], chunksize=chunk_size)

# Initialize lists to store processed chunks
games_chunks = []
rec_chunks = []
users_chunks = []

# Loop through chunks for each CSV file
for games_chunk, rec_chunk, users_chunk in zip(games_iter, rec_iter, users_iter):
    # Merge with other DataFrames if needed
    # Drop duplicate columns or perform other processing steps

    # Append processed chunks to the lists
    games_chunks.append(games_chunk)
    rec_chunks.append(rec_chunk)
    users_chunks.append(users_chunk)

# Concatenate all processed chunks for each CSV file
final_games = pd.concat(games_chunks, ignore_index=True)
final_rec = pd.concat(rec_chunks, ignore_index=True)
final_users = pd.concat(users_chunks, ignore_index=True)

# Concatenate the three DataFrames vertically
final_combined = pd.concat([final_games, final_rec, final_users], axis=0, ignore_index=True)

# Calculate processing time in seconds
end_time = time.time()
total_time_seconds = end_time - start_time
print(f"Processing Time: {total_time_seconds:.2f} seconds")

# Get RAM usage percentage
ram_percentage = psutil.virtual_memory().percent
print(f"System RAM Usage: {ram_percentage:.2f}%")

# Check the final_combined data size
final_games.info(memory_usage='deep')

Processing Time: 224.17 seconds
System RAM Usage: 7.40%
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50872 entries, 0 to 50871
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   app_id          50872 non-null  int64  
 1   title           50872 non-null  object 
 2   date_release    50872 non-null  object 
 3   win             50872 non-null  bool   
 4   mac             50872 non-null  bool   
 5   linux           50872 non-null  bool   
 6   rating          50872 non-null  object 
 7   positive_ratio  50872 non-null  int64  
 8   user_reviews    50872 non-null  int64  
 9   price_final     50872 non-null  float64
 10  price_original  50872 non-null  float64
 11  discount        50872 non-null  float64
 12  steam_deck      50872 non-null  bool   
dtypes: bool(4), float64(3), int64(3), object(3)
memory usage: 13.1 MB


###Optimize Data Types:
Fine-tune data types to maximize efficiency and minimize memory consumption.

Result after fine-tune data types as below:

*   Processing Time: 439.03 seconds
*   System RAM Usage After Conversion: 52.00%
*   Memory usage for df_game: 13.1 MB
*   Memory usage for df_rec: 4.1 GB
*   Memory usage for df_users: 315.6 MB










In [12]:
# Make copies of the original DataFrames
df_game_copy = df_game.copy()
df_rec_copy = df_rec.copy()
df_users_copy = df_users.copy()

# Convert columns in df_game_copy
df_game_copy['app_id'] = df_game_copy['app_id'].astype('uint32')
df_game_copy['date_release'] = pd.to_datetime(df_game_copy['date_release'])
df_game_copy['win'] = df_game_copy['win'].astype('bool')
df_game_copy['mac'] = df_game_copy['mac'].astype('bool')
df_game_copy['linux'] = df_game_copy['linux'].astype('bool')
df_game_copy['steam_deck'] = df_game_copy['steam_deck'].astype('bool')
df_game_copy['rating'] = df_game_copy['rating'].astype('category')
df_game_copy['positive_ratio'] = df_game_copy['positive_ratio'].astype('uint16')
df_game_copy['user_reviews'] = df_game_copy['user_reviews'].astype('uint32')
df_game_copy['price_final'] = df_game_copy['price_final'].astype('float32')
df_game_copy['price_original'] = df_game_copy['price_original'].astype('float32')
df_game_copy['discount'] = df_game_copy['discount'].astype('float32')

# Convert columns in df_rec_copy
df_rec_copy['app_id'] = df_rec_copy['app_id'].astype('uint32')
df_rec_copy['helpful'] = df_rec_copy['helpful'].astype('uint32')
df_rec_copy['funny'] = df_rec_copy['funny'].astype('uint32')
df_rec_copy['user_id'] = df_rec_copy['user_id'].astype('uint32')
df_rec_copy['review_id'] = df_rec_copy['review_id'].astype('uint32')
df_rec_copy['date'] = pd.to_datetime(df_rec_copy['date'])
df_rec_copy['is_recommended'] = df_rec_copy['is_recommended'].astype('bool')
df_rec_copy['hours'] = df_rec_copy['hours'].astype('float32')

# Convert columns in df_users_copy
df_users_copy['user_id'] = df_users_copy['user_id'].astype('uint32')
df_users_copy['products'] = df_users_copy['products'].astype('uint32')
df_users_copy['reviews'] = df_users_copy['reviews'].astype('uint32')

In [13]:
# Display system computing RAM (in percentage) after converting columns
ram_percentage_after_conversion = psutil.virtual_memory().percent
print(f"System RAM Usage After Conversion: {ram_percentage_after_conversion:.2f}%")

# Calculate processing time in seconds
end_time = time.time()
total_time_seconds = end_time - start_time
print(f"Processing Time: {total_time_seconds:.2f} seconds")

# Check the data size after conversion
df_game.info(memory_usage='deep')
df_rec.info(memory_usage='deep')
df_users.info(memory_usage='deep')

System RAM Usage After Conversion: 52.00%
Processing Time: 439.03 seconds
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50872 entries, 0 to 50871
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   app_id          50872 non-null  int64  
 1   title           50872 non-null  object 
 2   date_release    50872 non-null  object 
 3   win             50872 non-null  bool   
 4   mac             50872 non-null  bool   
 5   linux           50872 non-null  bool   
 6   rating          50872 non-null  object 
 7   positive_ratio  50872 non-null  int64  
 8   user_reviews    50872 non-null  int64  
 9   price_final     50872 non-null  float64
 10  price_original  50872 non-null  float64
 11  discount        50872 non-null  float64
 12  steam_deck      50872 non-null  bool   
dtypes: bool(4), float64(3), int64(3), object(3)
memory usage: 13.1 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38354101 entries, 0 t

###Sampling:
 Implement sampling methodologies to extract meaningful insights from a subset of the dataset.

Result 10% sample from DataFrame

*   Processing Time: 6.07 seconds
*   System RAM Usage: 41.50%
*   Memory usage: 2.1 GB




In [10]:
import pandas as pd
import numpy as np
import time
import psutil

# Record start time
start_time = time.time()

# Perform sampling on each DataFrame
sample_game = df_game.sample(frac=0.1, random_state=np.random.randint(10))
sample_rec = df_rec.sample(frac=0.1, random_state=np.random.randint(10))
sample_users = df_users.sample(frac=0.1, random_state=np.random.randint(10))

df_sampling = pd.concat([sample_game, sample_rec, sample_users])

end_time = time.time()
total_time_seconds = end_time - start_time
print(f"Processing Time: {total_time_seconds:.2f} seconds")

# Get RAM usage percentage
ram_percentage = psutil.virtual_memory().percent
print(f"System RAM Usage: {ram_percentage:.2f}%")

# Check the final_combined data size
df_sampling.info(memory_usage='deep')

Processing Time: 6.07 seconds
System RAM Usage: 41.50%
<class 'pandas.core.frame.DataFrame'>
Int64Index: 5219175 entries, 39005 to 9153188
Data columns (total 22 columns):
 #   Column          Dtype  
---  ------          -----  
 0   app_id          float64
 1   title           object 
 2   date_release    object 
 3   win             object 
 4   mac             object 
 5   linux           object 
 6   rating          object 
 7   positive_ratio  float64
 8   user_reviews    float64
 9   price_final     float64
 10  price_original  float64
 11  discount        float64
 12  steam_deck      object 
 13  helpful         float64
 14  funny           float64
 15  date            object 
 16  is_recommended  object 
 17  hours           float64
 18  user_id         float64
 19  review_id       float64
 20  products        float64
 21  reviews         float64
dtypes: float64(13), object(9)
memory usage: 2.1 GB


###Parallelize with Dask:
To extends pandas to enable parallel and distributed computing. It's particularly useful for handling larger-than-memory datasets.

Result of Parallelize with Dask:

*   RAM Usage: 4960.21 MB
*   Processing Time: 136.04 seconds
*   Total Size: 20.82 GB

In [ ]:
import dask
print(dask.__version__)

2023.8.1


In [ ]:
import dask.dataframe as dd

# List of CSV files
csv_files = ['/content/games.csv', '/content/recommendations.csv', '/content/users.csv']

# Read CSV files in parallel
dfs = [dd.read_csv(file) for file in csv_files]

# Use dask.dataframe.compute to trigger computation and get a list of pandas dataframes
pandas_dfs = dd.compute(*dfs)

# Now pandas_dfs is a list of pandas dataframes corresponding to each CSV file
games_df, recommendations_df, users_df = pandas_dfs

users_df.head(2)

user_id  products  reviews
0   7090995       359        0
1  13511788       156        1

In [ ]:
recommendations_df.head(2)

app_id  helpful  funny        date  is_recommended  hours  user_id  \
0  975370        0      0  2022-12-12            True   36.3    49625   
1  304390        4      0  2017-02-17           False   11.5     2482   

   review_id  
0          0  
1          1

In [ ]:
games_df.head(2)

app_id                              title date_release   win    mac  linux  \
0   13500  Prince of Persia: Warrior Within™   2008-11-21  True  False  False   
1   22364            BRINK: Agents of Change   2011-08-03  True  False  False   

          rating  positive_ratio  user_reviews  price_final  price_original  \
0  Very Positive              84          2199         9.99            9.99   
1       Positive              85            21         2.99            2.99   

   discount  steam_deck  
0       0.0        True  
1       0.0        True

In [ ]:
import dask.dataframe as dd
import time
import psutil  # This library helps to get system information

# Function to get RAM usage
def get_ram_usage():
    process = psutil.Process()
    return process.memory_info().rss / (1024 ** 2)  # in megabytes

# List of CSV files
csv_files = ['/content/games.csv', '/content/recommendations.csv', '/content/users.csv']

# Start measuring processing time
start_time = time.time()

# Read CSV files lazily
dfs = [dd.read_csv(file) for file in csv_files]

# Replace boolean values with 0 and 1
concatenated_dask['mac'] = concatenated_dask['mac'].replace({True: 1, False: 0})
concatenated_dask['linux'] = concatenated_dask['linux'].replace({True: 1, False: 0})
concatenated_dask['win'] = concatenated_dask['win'].replace({True: 1, False: 0})
concatenated_dask['steam_deck'] = concatenated_dask['steam_deck'].replace({True: 1, False: 0})

# Drop missing values
concatenated_dask = concatenated_dask.dropna().compute()

# Concatenate the dataframes
concatenated_dask = dd.concat(dfs, axis=0, ignore_index=True)

# End measuring processing time
end_time = time.time()

# Print RAM usage, processing time, and data size
print("RAM Usage: {:.2f} MB".format(get_ram_usage()))
print("Processing Time: {:.2f} seconds".format(end_time - start_time))

# Function to calculate the memory size of a partition
def calculate_partition_size(partition):
    return partition.memory_usage(deep=True).sum()

# Parallelize the task of calculating the size of each partition
partition_sizes = concatenated_dask.map_partitions(calculate_partition_size, meta=int).compute()

# Calculate the total size by summing up partition sizes
total_size = partition_sizes.sum()

# Display the result
print(f"Total Size: {total_size / (1024**3):.2f} GB")

concatenated_dask.head(2)


RAM Usage: 4960.21 MB
Processing Time: 136.04 seconds
Total Size: 20.82 GB
Final Result (Numeric):
     app_id                              title date_release   win    mac  \
0   13500.0  Prince of Persia: Warrior Within™   2008-11-21  True  False   
1   22364.0            BRINK: Agents of Change   2011-08-03  True  False   
2  113020.0       Monaco: What's Yours Is Mine   2013-04-24  True   True   
3  226560.0                 Escape Dead Island   2014-11-18  True  False   
4  249050.0            Dungeon of the ENDLESS™   2014-10-27  True   True   

   linux         rating  positive_ratio  user_reviews  price_final  ...  \
0  False  Very Positive            84.0        2199.0         9.99  ...   
1  False       Positive            85.0          21.0         2.99  ...   
2   True  Very Positive            92.0        3722.0        14.99  ...   
3  False          Mixed            61.0         873.0        14.99  ...   
4  False  Very Positive            88.0        8784.0        11.99  .

In [ ]:
final_result.head(2)

app_id  title  date_release   win    mac  linux  rating  positive_ratio  \
0    True   True          True  True  False  False    True            True   
1    True   True          True  True  False  False    True            True   

   user_reviews  price_final  ...  steam_deck  helpful  funny  date  \
0          True         True  ...        True     True   True  True   
1          True         True  ...        True     True   True  True   

   is_recommended  hours  user_id  review_id  products  reviews  
0            True   True     True       True      True     True  
1            True   True     True       True      True     True  

[2 rows x 22 columns]

##Data Understanding

Choose Parallelize with Dask strategy to process big data with explaination



In [ ]:
import pandas as pd
import dask.dataframe as dd
import time
import psutil  # This library helps to get system information

# Start measuring processing time
start_time = time.time()

# Define chunk size
chunk_size = 10000

# Create iterators for each CSV file
games_df= pd.read_csv('/content/games.csv', chunksize=chunk_size)
rec_df = pd.read_csv('/content/recommendations.csv', usecols=['app_id', 'helpful', 'funny', 'date', 'is_recommended', 'hours', 'user_id', 'review_id'], chunksize=chunk_size)
users_df = pd.read_csv('/content/users.csv', usecols=['user_id', 'products', 'reviews'], chunksize=chunk_size)

# Initialize lists to store processed chunks
games_chunks = []
rec_chunks = []
users_chunks = []

# Loop through chunks for each CSV file
for games_chunk, rec_chunk, users_chunk in zip(games_df, rec_df, users_df):
    # Merge with other DataFrames if needed
    # Drop duplicate columns or perform other processing steps

    # Append processed chunks to the lists
    games_chunks.append(games_chunk)
    rec_chunks.append(rec_chunk)
    users_chunks.append(users_chunk)

# Concatenate all processed chunks for each CSV file
games_df = pd.concat(games_chunks, ignore_index=True)
rec_df = pd.concat(rec_chunks, ignore_index=True)
users_df = pd.concat(users_chunks, ignore_index=True)

# Concatenate the three DataFrames vertically
final_combined = pd.concat([games_df, rec_df, users_df], axis=0, ignore_index=True)

# Calculate processing time in seconds
end_time = time.time()
total_time_seconds = end_time - start_time
print(f"Processing Time: {total_time_seconds:.2f} seconds")

# Get RAM usage percentage
ram_percentage = psutil.virtual_memory().percent
print(f"System RAM Usage: {ram_percentage:.2f}%")

# Check the final_combined data size
final_combined.info(memory_usage='deep')

Processing Time: 0.25 seconds
System RAM Usage: 30.40%
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170872 entries, 0 to 170871
Data columns (total 22 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   app_id          110872 non-null  float64
 1   title           50872 non-null   object 
 2   date_release    50872 non-null   object 
 3   win             50872 non-null   object 
 4   mac             50872 non-null   object 
 5   linux           50872 non-null   object 
 6   rating          50872 non-null   object 
 7   positive_ratio  50872 non-null   float64
 8   user_reviews    50872 non-null   float64
 9   price_final     50872 non-null   float64
 10  price_original  50872 non-null   float64
 11  discount        50872 non-null   float64
 12  steam_deck      50872 non-null   object 
 13  helpful         60000 non-null   float64
 14  funny           60000 non-null   float64
 15  date            60000 non-null   object 
 16  i

## Data Preprocessing

- Check for missing value
- Check for duplicate value

In [ ]:
# Check for missing values
missing_values = final_combined.isnull().sum()
print("Missing Values:")
print(missing_values)

Missing Values:
app_id             60000
title             120000
date_release      120000
win               120000
mac               120000
linux             120000
rating            120000
positive_ratio    120000
user_reviews      120000
price_final       120000
price_original    120000
discount          120000
steam_deck        120000
helpful           110872
funny             110872
date              110872
is_recommended    110872
hours             110872
user_id            50872
review_id         110872
products          110872
reviews           110872
dtype: int64


In [ ]:
# Drop rows with missing values in the "user_id" column
final_combined = final_combined.dropna(subset=['user_id'])

In [ ]:
# Drop rows with missing values in the "app_id" column
final_combined = final_combined.dropna(subset=['app_id'])

In [ ]:
#To check the missing percentage of 'date_release' column
missing_percentage = final_combined['date_release'].isnull().mean() * 100
print(f"Percentage of missing values in date_release: {missing_percentage:.2f}%")

Percentage of missing values in date_release: 100.00%


In [ ]:
# Foumd out that the missing value of column 'date_release' is 100%
# So decided to remove the 'date_release' column
final_combined= final_combined.drop('date_release', axis=1)
final_combined.head(2)

app_id title  win  mac linux rating  positive_ratio  user_reviews  \
50872  975370.0   NaN  NaN  NaN   NaN    NaN             NaN           NaN   
50873  304390.0   NaN  NaN  NaN   NaN    NaN             NaN           NaN   

       price_final  price_original  ...  steam_deck helpful  funny  \
50872          NaN             NaN  ...         NaN     0.0    0.0   
50873          NaN             NaN  ...         NaN     4.0    0.0   

             date is_recommended hours  user_id  review_id  products  reviews  
50872  2022-12-12           True  36.3  49625.0        0.0       NaN      NaN  
50873  2017-02-17          False  11.5   2482.0        1.0       NaN      NaN  

[2 rows x 21 columns]

In [ ]:
# List of columns to replace missing values
columns_to_replace = ['title', 'win', 'mac', 'linux', 'positive_ratio', 'user_reviews', 'rating',
                       'price_final', 'price_original', 'discount', 'steam_deck', 'products', 'reviews']

# Replace missing values with 'not available'
final_combined[columns_to_replace] = final_combined[columns_to_replace].fillna('not available')

In [ ]:
# Check for missing values
missing_values = final_combined.isnull().sum()
print("Missing Values:")
print(missing_values)

Missing Values:
app_id            0
title             0
win               0
mac               0
linux             0
rating            0
positive_ratio    0
user_reviews      0
price_final       0
price_original    0
discount          0
steam_deck        0
helpful           0
funny             0
date              0
is_recommended    0
hours             0
user_id           0
review_id         0
products          0
reviews           0
dtype: int64


In [ ]:
# Check for duplicate rows
print("\nDuplicate Rows in df_game:")
print(final_combined.duplicated().sum())


Duplicate Rows in df_game:
0


No duplicate value detected.\
So, no need to have further action.

##Process data types

In [ ]:
final_combined.head(2)

app_id          title            win            mac          linux  \
50872  975370.0  not available  not available  not available  not available   
50873  304390.0  not available  not available  not available  not available   

              rating positive_ratio   user_reviews    price_final  \
50872  not available  not available  not available  not available   
50873  not available  not available  not available  not available   

      price_original  ...     steam_deck helpful  funny        date  \
50872  not available  ...  not available     0.0    0.0  2022-12-12   
50873  not available  ...  not available     4.0    0.0  2017-02-17   

      is_recommended hours  user_id  review_id       products        reviews  
50872           True  36.3  49625.0        0.0  not available  not available  
50873          False  11.5   2482.0        1.0  not available  not available  

[2 rows x 21 columns]

In [ ]:
# Convert boolean columns to 0 and 1
problematic_rows = final_combined[final_combined['win'] == 'not available']
final_combined['win'] = final_combined['win'].replace('not available', 0).astype(int)
final_combined = final_combined[final_combined['win'] != 'not available']
final_combined['win'] = final_combined['win'].astype(int)

##Comparative Analysis

The provided output shows the resources and processing time for the chunked approach and the entire dataset approach.

1. Resources for final_combined_chunks:
The final_combined_chunks DataFrame has 60,651 entries and 22 columns.
It displays the non-null count and data types for each column.
The memory usage is reported as 22.9 MB.

2. Processing time for entire dataset:
The processing time for reading the entire dataset is 32.92 seconds.

3. Games DataFrame (Full):
The games_df_full DataFrame includes columns such as app_id, title, date_release, and others.
It provides information on game titles, release dates, compatibility, ratings, and pricing.
The date_release column has been converted to a datetime format.

4. Recommendations DataFrame (Full):
The rec_df_full DataFrame contains columns like app_id, helpful, funny, date, and others.
It includes information about user recommendations, helpful/funny votes, and review details.

5. Users DataFrame (Full):
The users_df_full DataFrame includes columns such as user_id, products, and reviews.
It provides information about user IDs, the number of products owned, and the number of reviews submitted.

Overall, the chunked approach allows you to process the data in smaller portions, reducing memory usage. However, it may require additional processing steps to handle chunks individually. The entire dataset approach loads the complete dataset into memory, which can be faster but may consume more resources.

In [ ]:
import pandas as pd

# Define chunk size
chunk_size = 10000

# Read the datasets using chunks
games_df = pd.read_csv('/content/games.csv', chunksize=chunk_size)
rec_df = pd.read_csv('/content/recommendations.csv', chunksize=chunk_size)
users_df = pd.read_csv('/content/users.csv', usecols=['user_id', 'products', 'reviews'], chunksize=chunk_size)

# Method 1: Using Chunks
def process_chunks():
    final_combined_chunks = pd.DataFrame()

    for games_chunk, rec_chunk, users_chunk in zip(games_df, rec_df, users_df):
        # Perform operations on each chunk
        combined_chunk = pd.merge(games_chunk, rec_chunk, on='app_id', how='left')
        combined_chunk = pd.merge(combined_chunk, users_chunk, on='user_id', how='left')

        # Concatenate chunks
        final_combined_chunks = pd.concat([final_combined_chunks, combined_chunk], ignore_index=True)

    return final_combined_chunks

# Method 2: Processing Entire Dataset by using Pandas (without merge)
def process_entire_dataset():
    # Read the entire datasets
    games_df_full = pd.read_csv('/content/games.csv')
    rec_df_full = pd.read_csv('/content/recommendations.csv')
    users_df_full = pd.read_csv('/content/users.csv', usecols=['user_id', 'products', 'reviews'])

    return games_df_full, rec_df_full, users_df_full

# Measure resources and processing time for chunks
final_combined_chunks = process_chunks()
print("Resources for final_combined_chunks:")
print(final_combined_chunks.info(memory_usage='deep'))
print("\n")

# Measure resources and processing time for entire dataset by using Pandas
start_time_entire = time.time()
games_df_full, rec_df_full, users_df_full = process_entire_dataset()
end_time_entire = time.time()
print(f"Processing time for entire dataset: {end_time_entire - start_time_entire} seconds")

# Display the first few rows of each DataFrame
print("Games DataFrame (Full):")
print(games_df_full.head())
print("\n")

print("Recommendations DataFrame (Full):")
print(rec_df_full.head())
print("\n")

print("Users DataFrame (Full):")
print(users_df_full.head())

Resources for final_combined_chunks:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60651 entries, 0 to 60650
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   app_id          60651 non-null  int64  
 1   title           60651 non-null  object 
 2   date_release    60651 non-null  object 
 3   win             60651 non-null  bool   
 4   mac             60651 non-null  bool   
 5   linux           60651 non-null  bool   
 6   rating          60651 non-null  object 
 7   positive_ratio  60651 non-null  int64  
 8   user_reviews    60651 non-null  int64  
 9   price_final     60651 non-null  float64
 10  price_original  60651 non-null  float64
 11  discount        60651 non-null  float64
 12  steam_deck      60651 non-null  bool   
 13  helpful         9977 non-null   float64
 14  funny           9977 non-null   float64
 15  date            9977 non-null   object 
 16  is_recommended  9977 non-null   object 

##Conclusion

In conclusion, the comparative analysis between different data processing strategies provides valuable insights into the trade-offs and benefits associated with each approach. The original data processing method, while simple and intuitive, may exhibit limitations in terms of memory usage and processing time, particularly when dealing with large datasets.

The choice of which strategy performs better depends on the specific analytical goals, dataset characteristics, and available resources. For large datasets, strategies like chunking, optimizing data types, and parallelizing with Dask tend to offer better performance in terms of reduced memory usage and faster processing times. However, for smaller datasets or quick exploratory analysis, simpler approaches like loading less data or using the original processing method may suffice. A combination of strategies may often yield the best results in balancing performance and resource efficiency.