<a href="https://colab.research.google.com/github/drshahizan/Python-big-data/blob/main/assignment/ass6/hpdp/MEOW/ass6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment 6: Mastering Big Data Handling

##Objective
In this assignment, we will explore the management of big data processing in data science. Big data processing involves the systematic handling and analysis of vast and complex datasets that exceed the capabilities of traditional data processing methods. It encompasses the storage, retrieval, and manipulation of massive volumes of information to extract valuable insights.

Group Members:
<div align="center">

| NAME | MATRICS NUMBER |
| :----: | :----: |
| NADIA SYAFIQAH BINTI ZULKIPLI | A21EC0098 |
| ALIYA ZARENA BINTI ZAINULANUAR | A21EC0013|




</div>

## 1.0 Dataset Selection

We able to find and retrieve a dataset from Kaggle, [Amazon Books Reviews](https://www.kaggle.com/datasets/mohamedbakhet/amazon-books-reviews) where we used both files with 1GB. This dataset is about feedback about 3 million users on 212404 unique books the data set is part of the Amazon review Dataset from May 1996 - July 2014.

## 2.0 Data Preparation & Cleaning

### 2.0.1 Import necessary libraries

In [ ]:
import pandas as pd
import numpy as np
import gc

### 2.0.2 Load dataset

Firstly, we will upload dataset by using Kaggle API

*   Import Kaggle API file



In [ ]:
from  google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"aliyazarena","key":"b9d04baf632d50acfad211a8389809a8"}'}

*   **files.upload()** is used to intiated a file upload dialog box which enable users to upload files. User have to navigate the intended file for upload, select the file and click **'Open'**




*   Install Kaggle Package

> Setting up Kaggle credentials on Google Colab allows interaction with the Kaggle API for dataset downloads.  This procedure allows users to access datasets without having to manually download them, which is very useful when dealing with large datasets.






In [ ]:
!pip install -q kaggle

In [ ]:
!mkdir -p ~/.kaggle #Create a Kaggle Directory
!cp kaggle.json ~/.kaggle/ #Upload the Kaggle API Token
!chmod 600 ~/.kaggle/kaggle.json #Set File Permission

*   Download the dataset

In [ ]:
!kaggle datasets download -d mohamedbakhet/amazon-books-reviews

100% 1.06G/1.06G [00:29<00:00, 40.8MB/s]
100% 1.06G/1.06G [00:29<00:00, 38.6MB/s]


*   Unzip the downloaded dataset

In [ ]:
!unzip amazon-books-reviews.zip

Archive:  amazon-books-reviews.zip
  inflating: Books_rating.csv        
  inflating: books_data.csv          


In [ ]:
path = 'Books_rating.csv'
df = pd.read_csv(path)

### 2.0.3 Explore dataset information

To explore the dataset columns name and the first five rows of the dataframe, we use **df.head()**

In [ ]:
df.head()

Id                           Title  Price         User_id  \
0  1882931173  Its Only Art If Its Well Hung!    NaN   AVCGYZL8FQQTD   
1  0826414346        Dr. Seuss: American Icon    NaN  A30TK6U7DNS82R   
2  0826414346        Dr. Seuss: American Icon    NaN  A3UH4UZ4RSVO82   
3  0826414346        Dr. Seuss: American Icon    NaN  A2MVUWT453QH61   
4  0826414346        Dr. Seuss: American Icon    NaN  A22X4XUPKF66MR   

                          profileName review/helpfulness  review/score  \
0               Jim of Oz "jim-of-oz"                7/7           4.0   
1                       Kevin Killian              10/10           5.0   
2                        John Granger              10/11           5.0   
3  Roy E. Perry "amateur philosopher"                7/7           4.0   
4     D. H. Richards "ninthwavestore"                3/3           4.0   

   review/time                                   review/summary  \
0    940636800           Nice collection of Julie Strain images   
1   1095724800                                Really Enjoyed It   
2   1078790400  Essential for every personal and Public Library   
3   1090713600  Phlip Nel gives silly Seuss a serious treatment   
4   1107993600                           Good academic overview   

                                         review/text  
0  This is only for Julie Strain fans. It's a col...  
1  I don't care much for Dr. Seuss but after read...  
2  If people become the books they read and if "t...  
3  Theodore Seuss Geisel (1904-1991), aka &quot;D...  
4  Philip Nel - Dr. Seuss: American IconThis is b...

<br>

We can get dataframe information via df.info(), such as column names, data types, entries, memory usage, and so on.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 10 columns):
 #   Column              Dtype  
---  ------              -----  
 0   Id                  object 
 1   Title               object 
 2   Price               float64
 3   User_id             object 
 4   profileName         object 
 5   review/helpfulness  object 
 6   review/score        float64
 7   review/time         int64  
 8   review/summary      object 
 9   review/text         object 
dtypes: float64(2), int64(1), object(7)
memory usage: 228.9+ MB


In [ ]:
#To determine the number of items (cells) in a dataframe
df.size

30000000

In [ ]:
#To analyze the dataframe's rows and columns
df.shape

(3000000, 10)

In [ ]:
#Descriptive statistics
df.describe()

Price  review/score   review/time
count  481171.000000  3.000000e+06  3.000000e+06
mean       21.762656  4.215289e+00  1.132307e+09
std        26.206541  1.203054e+00  1.493202e+08
min         1.000000  1.000000e+00 -1.000000e+00
25%        10.780000  4.000000e+00  9.999072e+08
50%        14.930000  5.000000e+00  1.128298e+09
75%        23.950000  5.000000e+00  1.269130e+09
max       995.000000  5.000000e+00  1.362355e+09

The table above summarizes all of the statistics for the relevant numerical variables, such as mean, median, standard deviation, and quantiles.

### 2.0.4 Handle missing values

This procedure entails locating and addressing missing or null values in the dataset to maintain data integrity and eliminate potential biases or inconsistencies in the analysis caused by the absence of information in specific entries.

*   Check for the missing data for each column

In [ ]:
#Check missing data
df.isna().sum()

Id                          0
Title                     208
Price                 2518829
User_id                561787
profileName            561886
review/helpfulness          0
review/score                0
review/time                 0
review/summary             38
review/text                 8
dtype: int64

*   Handle the missing values by dropping it from the dataframe

In [ ]:
#Handle missing values
df = df.dropna()

*   Double check the missing data after drop it

In [ ]:
#Check missing data
df.isna().sum()

Id                    0
Title                 0
Price                 0
User_id               0
profileName           0
review/helpfulness    0
review/score          0
review/time           0
review/summary        0
review/text           0
dtype: int64

### 2.0.5 Remove duplicates

This function used to remove the duplicates rows that were found in the dataframe.

In [ ]:
def drop_duplicates(df):
    old = df.shape[0]
    df.drop_duplicates(inplace=True)
    new = df.shape[0]
    count = old - new
    if (count == 0):
        print("No duplicate rows were found.")
    else:
        print(f"{count} duplicate rows were found and removed.")

In [ ]:
drop_duplicates(df)

500 duplicate rows were found and removed.


##3.0 Strategies for Big Datasets

### 3.0.1 Load Less Data

By loading only the essential portions of the dataset to optimize memory usage.

In [ ]:
#Display the columns name of the dataframe to ensure accurate selected columns used
df.columns

Index(['Id', 'Title', 'Price', 'User_id', 'profileName', 'review/helpfulness',
       'review/score', 'review/time', 'review/summary', 'review/text'],
      dtype='object')

In [ ]:
used_columns = ['Title', 'review/helpfulness', 'review/score', 'review/time', 'review/text']

In [ ]:
df_less_data = pd.read_csv(path, usecols = used_columns)

In [ ]:
df_less_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 5 columns):
 #   Column              Dtype  
---  ------              -----  
 0   Title               object 
 1   review/helpfulness  object 
 2   review/score        float64
 3   review/time         int64  
 4   review/text         object 
dtypes: float64(1), int64(1), object(3)
memory usage: 114.4+ MB


From the above info, we can observed that the memory usgae is being reduced from 228.9+ MB to 114.4+ MB.

### 3.0.2 Use Chunking

When datasets are too massive to be loaded and processed at once due to memory constraints, chunking allows breaking down the dataset into smaller, more manageable portions or chunks. Each chunk can be processed independently, enabling analysis, manipulation, or modeling on parts of the dataset without requiring the entire dataset to be held in memory simultaneously.

In [ ]:
chunk_size = 500000
num = 1
for chunk in pd.read_csv(path, chunksize = chunk_size):
  chunk.to_csv('chunk'+str(num)+'.csv', index = False)
  gc.collect()
  num+=1

After chuncking, see whether we can read the chunk and check the info.

In [ ]:
df = pd.read_csv('chunk1.csv')
df.head()

Id                           Title  Price         User_id  \
0  1882931173  Its Only Art If Its Well Hung!    NaN   AVCGYZL8FQQTD   
1  0826414346        Dr. Seuss: American Icon    NaN  A30TK6U7DNS82R   
2  0826414346        Dr. Seuss: American Icon    NaN  A3UH4UZ4RSVO82   
3  0826414346        Dr. Seuss: American Icon    NaN  A2MVUWT453QH61   
4  0826414346        Dr. Seuss: American Icon    NaN  A22X4XUPKF66MR   

                          profileName review/helpfulness  review/score  \
0               Jim of Oz "jim-of-oz"                7/7           4.0   
1                       Kevin Killian              10/10           5.0   
2                        John Granger              10/11           5.0   
3  Roy E. Perry "amateur philosopher"                7/7           4.0   
4     D. H. Richards "ninthwavestore"                3/3           4.0   

   review/time                                   review/summary  \
0    940636800           Nice collection of Julie Strain images   
1   1095724800                                Really Enjoyed It   
2   1078790400  Essential for every personal and Public Library   
3   1090713600  Phlip Nel gives silly Seuss a serious treatment   
4   1107993600                           Good academic overview   

                                         review/text  
0  This is only for Julie Strain fans. It's a col...  
1  I don't care much for Dr. Seuss but after read...  
2  If people become the books they read and if "t...  
3  Theodore Seuss Geisel (1904-1991), aka &quot;D...  
4  Philip Nel - Dr. Seuss: American IconThis is b...

### 3.0.3 Optimize Data Types

We need to review the dataset information for the columns and their data types.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   Id                  500000 non-null  object 
 1   Title               499993 non-null  object 
 2   Price               80099 non-null   float64
 3   User_id             403654 non-null  object 
 4   profileName         403642 non-null  object 
 5   review/helpfulness  500000 non-null  object 
 6   review/score        500000 non-null  float64
 7   review/time         500000 non-null  int64  
 8   review/summary      499996 non-null  object 
 9   review/text         499999 non-null  object 
dtypes: float64(2), int64(1), object(7)
memory usage: 38.1+ MB


We can see from the information that there are 2 columns with float64. One of the most common problems with pandas is that it constantly loads float data as float64. We may have lowered the size of our dataset by optimizing this memory. To save memory, we must convert it to **'float16'** or **'float32'**. Here, we will convert it to **'float16'**.

Not only that, column that have data type of 'int64' will also be converted to **'int16'**.


In [ ]:
for column in df.columns:
  if df[column].dtype == 'float64':
    df[column] = df[column].astype('float16')
  if df[column].dtype == 'int64':
    df[column] = df[column].astype('int16')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   Id                  500000 non-null  object 
 1   Title               499993 non-null  object 
 2   Price               80099 non-null   float16
 3   User_id             403654 non-null  object 
 4   profileName         403642 non-null  object 
 5   review/helpfulness  500000 non-null  object 
 6   review/score        500000 non-null  float16
 7   review/time         500000 non-null  int16  
 8   review/summary      499996 non-null  object 
 9   review/text         499999 non-null  object 
dtypes: float16(2), int16(1), object(7)
memory usage: 29.6+ MB


As you can see, the memory usage has been reduced to 29.6+ MB from 38.1+ MB.

### 3.0.4 Sampling

Sampling data known as choosing a selection of samples from a larger dataset in order to draw conclusions about the wider population from which the data is derived. Because it enables analysts to make inferences about a population without having to examine the complete dataset, which may be difficult or time-consuming, sampling is an essential tool in statistics and data analysis. In this case study, we choose two types of sampling which is **simple random sampling** and **stratified sampling**.









#### 3.0.4.1 Simple Random Sampling

Using simple random sampling, every segment of the population has an equal chance of being selected for the sample. It can be used on our dataset's numeric and categorical columns.


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   Id                  500000 non-null  object 
 1   Title               499993 non-null  object 
 2   Price               80099 non-null   float16
 3   User_id             403654 non-null  object 
 4   profileName         403642 non-null  object 
 5   review/helpfulness  500000 non-null  object 
 6   review/score        500000 non-null  float16
 7   review/time         500000 non-null  int16  
 8   review/summary      499996 non-null  object 
 9   review/text         499999 non-null  object 
dtypes: float16(2), int16(1), object(7)
memory usage: 29.6+ MB


In [ ]:
#This is the default method in sampling
#It will select one row from the dataset randomly

df.sample()

Id                                              Title  \
379248  1932183043  Searchings: Secret Landscapes of Flowers, Vol. II   

          Price         User_id profileName review/helpfulness  review/score  \
379248  28.0625  A328S9RN3U5M68  Grady Harp              13/14           5.0   

        review/time                                review/summary  \
379248       -17664  Exploring the Sensual Landscape of the Flora   

                                              review/text  
379248  Barbara Bordnick is a fine photographer who ha...

Example 1: We can try to choose two random rows by using the **"n" parameter** too and compare the results.

In [ ]:
#1ST ROW:

# generating one row
first_row = df.sample(n = 1)

# display the first random row
first_row

Id                            Title  Price User_id  \
188800  0460112872  Jane Eyre (Everyman's Classics)    NaN     NaN   

       profileName review/helpfulness  review/score  review/time  \
188800         NaN                0/0           4.0        -9088   

                              review/summary  \
188800  Too many coincidences but a fun book   

                                              review/text  
188800  It's easy to understand and it starts to get f...

In [ ]:
#2ND ROW:

# generating another row
sec_row = df.sample(n = 1)

# display the second random row
sec_row

Id          Title  Price        User_id   profileName  \
464587  B000Q751JC  War In Heaven    NaN  A7YQ2UR3X3YPB  john shirley   

       review/helpfulness  review/score  review/time  \
464587               9/10           5.0       -19712   

                                       review/summary  \
464587  Charles Williams - meaningful and influential   

                                              review/text  
464587  Some people 'get it' and some don't. CS Lewis ...

Based on both results, we can see that:
- Both have a review score of 5.0, suggesting that users rated both books highly.
- The first entry's "Review Helpfulness" score is 0/2, meaning that two people voted it helpful and none against. With a score of 0/0, the second entry is unvoted.

Example 2: We use **"frac" parameter** to specify the fractions of rows and columns. In this case, we will be using 25% sample of data frame. You may adjust the frac based on your preference.

In [ ]:
# generating new dataset with the fraction of 25%
# 25% = 0.25

frac_row = df.sample(frac = 0.25)
frac_row

Id                                              Title  \
446493  0460872702                            Great Gatsby (Everyman)   
367235  0811813592                                         Shortbread   
466153  093949566X                                       Silas Marner   
140328  B0007PC4ZM  Collapse: How Societies Choose to Fail or Succeed   
6398    B0006DG9OM  Tess of the D'Urbervilles: A pure woman (Harpe...   
...            ...                                                ...   
163061  B000L2Z5TS                                   Inherit the Wind   
267747  B0006X36CU                    The Best Christmas pageant ever   
181959  B00070X460  Diary of an old soul: 366 writings for devotio...   
416440  0517124203                   Alice's Adventures in Wonderland   
357013  0435126024                           Jane Eyre (New Windmill)   

            Price         User_id                  profileName  \
446493        NaN  A1EX6Z7F0VSP3X                        Renee   
367235        NaN  A3LSTV122F9Y41            Matiqua "matiqua"   
466153  26.000000  A1JTG5X4VHJV27         Plume45 "kitka12345"   
140328        NaN  A39WMF96QORN95  Jeff Durbin "jeffreydurbin"   
6398          NaN             NaN                          NaN   
...           ...             ...                          ...   
163061        NaN             NaN                          NaN   
267747        NaN             NaN                          NaN   
181959        NaN  A10086RBUG195A              David Friedrich   
416440        NaN  A19FUQGN6TH1M6              By E. R. Schill   
357013  14.023438             NaN                          NaN   

       review/helpfulness  review/score  review/time  \
446493                1/6           2.0       -14976   
367235              10/10           5.0        25216   
466153                2/2           3.0        19840   
140328              15/24           3.0        -1664   
6398                  0/0           4.0        32000   
...                   ...           ...          ...   
163061                1/2           5.0        31360   
267747                0/0           5.0       -30080   
181959                3/4           5.0         8448   
416440                0/0           4.0        15872   
357013                2/2           5.0        22144   

                                           review/summary  \
446493                                            Tedious   
367235                                  Shortbread magic!   
466153                            MORE PRECIOUS THAN GOLD   
140328         Lots of good points but a few key failings   
6398                       Best book forced to read......   
...                                                   ...   
163061         A historical allegory for the human spirit   
267747                                        Very funny!   
181959                          Honesty, Beauty and Depth   
416440                                     Very confusing   
357013  Jane is my role model! I give this book ******...   

                                              review/text  
446493  I am not certain why this book is considered a...  
367235  I love this book! The recipes are really easy ...  
466153  This 19th century classic by George Eliot/Mary...  
140328  First of all, Jared Diamond states in the pref...  
6398    Out of all the book I was forced to read...I L...  
...                                                   ...  
163061  I read Inherit The Wind my sophomore year of h...  
267747  I think this is a great book! I liked it becau...  
181959  If you want to be led out of your darkness and...  
416440  It was a good book, and a good classic. Most o...  
357013  This book is about a girl named Jane Eyre, who...  

[125000 rows x 10 columns]

In [ ]:
#A method to check whether the result is 0.25 times of dataset or not
if (0.25*(len(df)) == len(frac_row)):
    print( "This is the sample with 25% fraction")
    print(f"The size of original dataset: {len(df)} while " + f"the size of fraction dataset: {len(frac_row)}")
else:
    print("This is not the sample with 25% fraction")
    print(f"The size of original dataset: {len(df)} while " + f"the size of fraction dataset: {len(frac_row)}")

This is the sample with 25% fraction
The size of original dataset: 500000 while the size of fraction dataset: 125000


#### 3.0.4.2 Stratified Sampling
Using stratified sampling, the population is divided into several subgroups (*strata*) according to specific criteria. Next, from each stratum which called as *singular form of strata*, a random sample is being taken then.

Example: We select 10 rows from the records where we want to sample out 8 rows based on the "review/score" column

In [ ]:
#select 10 random rows

rows = df.sample(n = 10)
rows

Id                                              Title  \
74364   B0001GDR3U                                     The Last Juror   
300142  0658000772  Beginner's Arabic Script: An Introduction to R...   
75622   0786280670  Julie and Julia: 365 Days, 524 Recipes, 1 Tiny...   
213488  B000F5X89K                                       Frankenstein   
461404  B00087QGG2                             Police at the funeral,   
474431  B000JJVHZE                              To Kill A Mockingbird   
319031  B0006AP72A                        Murder in the Calais coach,   
405480  B000NVO78W                                               City   
422891  0736619453   Edmund Campion: Scholar, Priest, Hero And Martyr   
210264  0740742752                                  Get Fuzzy Journal   

           Price         User_id  \
74364        NaN  A2FIGHUA3B2HRZ   
300142       NaN             NaN   
75622        NaN  A3OL1AX1IODBYL   
213488       NaN  A39EWLFPK1N7X8   
461404       NaN  A1THI0Q54LD3UT   
474431       NaN  A19YYWFJJ3S9NA   
319031       NaN  A32VWSQ0FPZKZ3   
405480       NaN  A2WGXE8JPTWYUL   
422891       NaN   ACP5CQC6JVPPS   
210264  9.953125             NaN   

                                         profileName review/helpfulness  \
74364                                   B. R. Tooley                1/1   
300142                                           NaN              17/17   
75622   Laurel-Rain Snow &#34;Rain&#34; "Rainy Days"                2/4   
213488                                       David P                0/0   
461404    J. Bonner "Vamp and British mystery lover"                0/2   
474431                                     Rita Wong                1/1   
319031                                           MAB                0/0   
405480                            Michael Austerlitz                0/0   
422891                                      Alan Ebi                0/2   
210264                                           NaN              40/41   

        review/score  review/time                    review/summary  \
74364            5.0       -11264                      A Great read   
300142           5.0       -29312           Fast-paced introduction   
75622            5.0        28544            LIVING LIFE WITH GUSTO   
213488           4.0        -8576  Dry at times but still a classic   
461404           5.0       -12288                         Excellent   
474431           5.0        21504                        Great Book   
319031           4.0        18048  Enjoyable to read on a vacation.   
405480           5.0         9728             Insanely good sci-fi.   
422891           5.0         9216               Martyr to progress?   
210264           5.0        12416                A few things . . .   

                                              review/text  
74364   I really enjoyed this book. It reminded me of ...  
300142  Packed with examples, this book doesn't just p...  
75622   I loved the movie, and even though I usually r...  
213488  I wanted to read much of the free books with m...  
461404  I enjoyed this book very much, so much that I'...  
474431  It's as if I read it in high school. Love Scou...  
319031  &quot;Murder on the Orient Express&quot; is an...  
405480  I bought this as I had to read a short story f...  
422891  Evelyn Waugh's Edmund Campion is about the mak...  
210264  This is in response to salerwee's review.1.) N...

1st Method: Disproportionate Sampling

The sample size of each stratum is equal irrespective of the population size of the stratum. Here, we separate the records into groups based on "review/score" where sampling 3 random from each score

In [ ]:
# Group the DataFrame by 'review/score'
grouped = rows.groupby('review/score', group_keys=False)

# To sample 3 rows from each group
grouped_rows = grouped.apply(lambda x: x.sample(min(3, len(x))))

grouped_rows

Id                                              Title  Price  \
213488  B000F5X89K                                       Frankenstein    NaN   
319031  B0006AP72A                        Murder in the Calais coach,    NaN   
422891  0736619453   Edmund Campion: Scholar, Priest, Hero And Martyr    NaN   
461404  B00087QGG2                             Police at the funeral,    NaN   
300142  0658000772  Beginner's Arabic Script: An Introduction to R...    NaN   

               User_id                                 profileName  \
213488  A39EWLFPK1N7X8                                     David P   
319031  A32VWSQ0FPZKZ3                                         MAB   
422891   ACP5CQC6JVPPS                                    Alan Ebi   
461404  A1THI0Q54LD3UT  J. Bonner "Vamp and British mystery lover"   
300142             NaN                                         NaN   

       review/helpfulness  review/score  review/time  \
213488                0/0           4.0        -8576   
319031                0/0           4.0        18048   
422891                0/2           5.0         9216   
461404                0/2           5.0       -12288   
300142              17/17           5.0       -29312   

                          review/summary  \
213488  Dry at times but still a classic   
319031  Enjoyable to read on a vacation.   
422891               Martyr to progress?   
461404                         Excellent   
300142           Fast-paced introduction   

                                              review/text  
213488  I wanted to read much of the free books with m...  
319031  &quot;Murder on the Orient Express&quot; is an...  
422891  Evelyn Waugh's Edmund Campion is about the mak...  
461404  I enjoyed this book very much, so much that I'...  
300142  Packed with examples, this book doesn't just p...

2nd Method: Proportionate Sampling

The sample size of each stratum is proportional to the population size of the stratum.


In [ ]:
# Sample 80% of records proportionately
# 80% = 0.8
grouped_rows_frac = rows.groupby('review/score', group_keys=False).apply(lambda x: x.sample(frac=0.8))
grouped_rows_frac

Id                                              Title  Price  \
319031  B0006AP72A                        Murder in the Calais coach,    NaN   
213488  B000F5X89K                                       Frankenstein    NaN   
474431  B000JJVHZE                              To Kill A Mockingbird    NaN   
422891  0736619453   Edmund Campion: Scholar, Priest, Hero And Martyr    NaN   
75622   0786280670  Julie and Julia: 365 Days, 524 Recipes, 1 Tiny...    NaN   
74364   B0001GDR3U                                     The Last Juror    NaN   
461404  B00087QGG2                             Police at the funeral,    NaN   
405480  B000NVO78W                                               City    NaN   

               User_id                                   profileName  \
319031  A32VWSQ0FPZKZ3                                           MAB   
213488  A39EWLFPK1N7X8                                       David P   
474431  A19YYWFJJ3S9NA                                     Rita Wong   
422891   ACP5CQC6JVPPS                                      Alan Ebi   
75622   A3OL1AX1IODBYL  Laurel-Rain Snow &#34;Rain&#34; "Rainy Days"   
74364   A2FIGHUA3B2HRZ                                  B. R. Tooley   
461404  A1THI0Q54LD3UT    J. Bonner "Vamp and British mystery lover"   
405480  A2WGXE8JPTWYUL                            Michael Austerlitz   

       review/helpfulness  review/score  review/time  \
319031                0/0           4.0        18048   
213488                0/0           4.0        -8576   
474431                1/1           5.0        21504   
422891                0/2           5.0         9216   
75622                 2/4           5.0        28544   
74364                 1/1           5.0       -11264   
461404                0/2           5.0       -12288   
405480                0/0           5.0         9728   

                          review/summary  \
319031  Enjoyable to read on a vacation.   
213488  Dry at times but still a classic   
474431                        Great Book   
422891               Martyr to progress?   
75622             LIVING LIFE WITH GUSTO   
74364                       A Great read   
461404                         Excellent   
405480             Insanely good sci-fi.   

                                              review/text  
319031  &quot;Murder on the Orient Express&quot; is an...  
213488  I wanted to read much of the free books with m...  
474431  It's as if I read it in high school. Love Scou...  
422891  Evelyn Waugh's Edmund Campion is about the mak...  
75622   I loved the movie, and even though I usually r...  
74364   I really enjoyed this book. It reminded me of ...  
461404  I enjoyed this book very much, so much that I'...  
405480  I bought this as I had to read a short story f...

Based on the both methods, we can analyze that the **"review/score"** for 5.0 and 4.0 is holding 37.5% each, while as for 2.0 and 1.0 is holding 12.5% each. Moreover, we can see there is no score of 3.0 because refer to the selected 10 random samples does not contain score of 3.0

### 3.0.5 Parallelize with Dask

In [ ]:
!pip install dask

In [ ]:
# We can check the detail information about Dask package
!pip show dask

Name: dask
Version: 2023.8.1
Summary: Parallel PyData with Task Scheduling
Home-page: 
Author: 
Author-email: 
License: BSD-3-Clause
Location: /usr/local/lib/python3.10/dist-packages
Requires: click, cloudpickle, fsspec, importlib-metadata, packaging, partd, pyyaml, toolz
Required-by: distributed


In [ ]:
# Import dask and other necessary libraries
import dask
import dask.dataframe as dd
from dask.diagnostics import ProgressBar

In [ ]:
#Load data with dask
# Specify the dtype for the 'Id' column
dtype = {'Id': 'object'}
# Read the CSV file with specified dtype
file_path = 'Books_rating.csv'
dask_df = dd.read_csv(file_path,dtype=dtype)
dask_df

Dask DataFrame Structure:
                    Id   Title    Price User_id profileName review/helpfulness review/score review/time review/summary review/text
npartitions=44                                                                                                                    
                object  object  float64  object      object             object      float64       int64         object      object
                   ...     ...      ...     ...         ...                ...          ...         ...            ...         ...
...                ...     ...      ...     ...         ...                ...          ...         ...            ...         ...
                   ...     ...      ...     ...         ...                ...          ...         ...            ...         ...
                   ...     ...      ...     ...         ...                ...          ...         ...            ...         ...
Dask Name: read-csv, 1 graph layer

In loading dataset, dask have same functionality "read.csv' with the pandas, but in dask, it allows to operate on large memory datasets compared to pandas. We can see that pandas take 46 seconds to load the data while the dask only takes 0 seconds to complete run it.

In [ ]:
dask_df.columns

Index(['Id', 'Title', 'Price', 'User_id', 'profileName', 'review/helpfulness',
       'review/score', 'review/time', 'review/summary', 'review/text'],
      dtype='object')

In [ ]:
# Check for any missing values
missing_values_count = dask_df.isna().sum().compute()
missing_values_count

Id                          0
Title                     208
Price                 2518829
User_id                561787
profileName            561886
review/helpfulness          0
review/score                0
review/time                 0
review/summary             38
review/text                 8
dtype: int64

In [ ]:
# Handle missing values
dask_df = dask_df.dropna()
check_missing_value_count = dask_df.isna().sum().compute()
check_missing_value_count

Id                    0
Title                 0
Price                 0
User_id               0
profileName           0
review/helpfulness    0
review/score          0
review/time           0
review/summary        0
review/text           0
dtype: int64

Example: Calculates the mean of the 'review/score' based on the 'User_id' column in parallel across Dask partitions.

In [ ]:
import time

# Record the start time
start_time = time.time()

mean_score = dask_df.groupby('User_id')['review/score'].mean()

In [ ]:
# Trigger computation and display result
result = mean_score.compute()
print(f"Mean Review Score: {result}")

Mean Review Score: User_id
A00940571GAOITYS675AR    4.000000
A0147018299H7B1MXYFW1    5.000000
A02355172J55BBI6MHY9G    5.000000
A100627LB08AVD           5.000000
A100NGGXRQF0AQ           3.571429
                           ...   
AZWNQI4V03Q98            1.000000
AZX1I17HYBQ0Q            3.000000
AZYGA464FN61Y            5.000000
AZYMT1CZ1YC4X            5.000000
AZZSG2P8CE9RY            4.000000
Name: review/score, Length: 305452, dtype: float64


Based on the results, the 'User_id' column displays the mean review scores for every unique user, which represent the overall mood of their reviews. The values fall between 1.0 and 5.0, with higher numbers correspond to more favourable ratings.

Example: How the parallelization with Dask works.

Note: Initial functions for calculating the mean review score would remain the SAME

In [ ]:
import dask
from dask import delayed

In [ ]:
complex_result = dask_df.groupby('User_id')['review/score'].mean()

In [ ]:
parallelize_score = delayed(complex_result)
parallelize_score

Delayed('Series-fcfb94af-d9e1-4a87-96d4-da42be6180fc')

As we can see above, it wont show the value of parallelize score, therefore we need to apply *compute()* function in order to get the result. We can also use *visualize()* function to see the parallel execution will look like.

In [ ]:
parallelize_score.visualize()

In [ ]:
new_result = parallelize_score.compute()
print(f"Mean Review Score: {new_result}")

Mean Review Score: User_id
A00940571GAOITYS675AR    4.000000
A0147018299H7B1MXYFW1    5.000000
A02355172J55BBI6MHY9G    5.000000
A100627LB08AVD           5.000000
A100NGGXRQF0AQ           3.571429
                           ...   
AZWNQI4V03Q98            1.000000
AZX1I17HYBQ0Q            3.000000
AZYGA464FN61Y            5.000000
AZYMT1CZ1YC4X            5.000000
AZZSG2P8CE9RY            4.000000
Name: review/score, Length: 305452, dtype: float64


We can see that the results from pandas and Dask are similar; however, the difference is that Dask can manage several pandas dataframes and store them if memory is limited. Furthermore, dask provides a delayed approach for parallelizing execution, allowing data storage to be used more efficiently.

In [ ]:
# Record the end time
end_time = time.time()

# Calculate the elapsed time
elapsed_time = end_time - start_time

# Calculate the memory usage of the Dask DataFrame
memory_usage = dask_df.memory_usage(deep=True).compute()

print(f"Memory Usage: {memory_usage}")
print(f"The Elapsed Time to calculate the mean review score by Dask: {elapsed_time} seconds")

Memory Usage: Id                     27774716
Index                   3316384
Price                   3316384
Title                  44612701
User_id                29323227
profileName            30192565
review/helpfulness     25027865
review/score            3316384
review/summary         35287491
review/text           370968655
review/time             3316384
dtype: int64
The Elapsed Time to calculate the mean review score by Dask: 283.15247774124146 seconds


## 4.0 Comparative Analysis

Table 1 below shows the comparison between traditional methods and advanced strategies in several aspects for handling big datasets.

| Aspect | Traditional Methods | Advanced Strategies(Dask) |
| -------- | -------- | -------- |
| **Memory Usage** | High | Optimized at each step |
| **Computation Time** | Longer processing time | Varies depending on the steps as some steps may be faster |
| **File Size** | Large | Smaller chunked / optimized files |
| **Handling NaNs** | Drop NaN values | Handle missing values as needed |
| **Load Dataset** | Loads entire dataset into memory | Loads essential columns only |
| **Data Types** | Unoptimized data types | Optimized data types for efficiency|
| **Sampling**         | Longer time processing              | Implemented for subset analysis   |
| **Parallelization**  | Not utilized(limited)                   | Faster and efficient completion of tasks |


<div align="center">

**Table 1**
</div>

<br>

Here are meaningful insights into the advantages gained through the adoption of those strategies:



a) Memory Efficiency
*  Loading less data and optimizing data types result in a significantly smaller memory footprint than the traditional approach.
*   Chunking and optimized data types significantly decrease memory usage which enable efficient storage and manipulation of large datasets without exhausting system resources.

<br>

b) Computation Time
*   Techniques such as chunking and parallelization (with Dask) result in faster processing speeds by allowing operations to be executed concurrently on smaller subsets or across several processors.

<br>

c) File Size Reduction
*   Chunked files and optimized datasets occupy considerably smaller storage space compared to the original dataset. This reduction in file size simplifies data management and storage.

<br>

d) Parallel Computing
*   Utilizing Dask for parallel computing enables distributed and parallel execution, leveraging multicore processors or distributed computing clusters for faster computations and analysis of large-scale datasets.

<br>

e) Scalability & Flexibility
*   Advanced strategies facilitate scalability by enabling the processing of larger datasets without overwhelming system resources.
*   The ability to perform analysis on smaller subsets (sampling) or chunks of data allows for more flexible and iterative analysis without the need to load the entire dataset.














## 5.0 Conclusion

The adoption of advanced strategies in handling big data offers substantial improvements in memory efficiency, computation speed, file size reduction, data quality, scalability, and parallel processing capabilities. These advantages empower data scientists and analysts to efficiently manage, process, and derive insights from massive and complex datasets, overcoming the limitations of traditional methods and enhancing the overall productivity and effectiveness of data-driven decision-making processes. Several key strategies include:

1. **Load Less Data:**
   - By utilising the `usecols` parameter to define a subset of columns ({['Title','review/helpfulness','review/score',
   'review/time','review/text']}), the code snippet loads less data from a CSV file. The result of DataFrame ({df_less_data}) minimises it's memory footprint and speeds up data loading and processing by selectively loading only the relevant columns. Enhancing overall efficiency is a benefit of this strategy, particularly when dealing with huge datasets when analysis may not require all columns. A more effective data handling strategy is facilitated by the reduced data amount, which enables faster exploratory data analysis as well as more streamlined and resource-efficient operations.

2. **Chunking:**
   - In the provided code, chunking is implemented using the pandas `Books_rating.csv` function with a specified chunk size of `500,000 rows.` To enable more managed and parallelized processing, each chunk read from the big dataset is saved as a distinct CSV file `(e.g., "chunk1.csv," "chunk2.csv").` This method reduces memory needs, permits parallelized actions on each chunk, and facilitates more efficient processing by dividing the dataset into smaller, more manageable pieces. Additionally, memory management during the iterative reading and storing of chunks is aided by the explicit memory release performed by the `gc.collect()` method after each chunk is completed.

3. **Optimize Data Types:**
   - To reduce the DataFrame's memory footprint, the code downcasts data types to more memory-efficient formats like `float16` and `int16.` This benefits in terms of having lesser storage needs, quicker calculations, and better overall performance—particularly with big datasets. Although reducing the size of data types may lead to a decrease in accuracy, this is frequently a trade-off that should be taken into account when aiming for memory economy, especially when the precision loss has little effect on the analysis or outcomes. When working with datasets whose numeric columns take up a lot of RAM in their native formats, this optimisation is quite helpful.

4. **Sampling:**
   - Sampling is a crucial data analysis strategy, with two main techniques being simple random sampling and stratified sampling based on the `"review/score" column.` In contrast, simple random sampling is straightforward, stratified sampling provides a more targeted approach, especially in heterogeneous populations, ensuring accurate representation of diverse groups. Both methods contribute to more efficient data analysis by allowing manageable subsets for processing.

5. **Parallelize with Dask:**
   - Dask makes it possible to parallelize processes effectively, which boosts overall performance and processing speed. Furthermore, Dask gives users fine-grained control over parallel execution with tools like `delayed()`, which let them directly specify and manage calculations. Through the creation of a graph visualisation of the task dependencies, Dask's `visualise()` function facilitates comprehension and optimisation of the parallelized computation. When combined, these characteristics give Dask great power to scale computations and data analysis across distributed computing environments.